### ISSUE TITLE
Mesh files

### ISSUE THREAD

**Issue by fjp** [NestorDP/littlebot#7]
Hi @NestorDP thanks for creating Littlebot it looks great. @pxalcantara pointed me to your repo because I am working on a similar project called [DiffBot](https://github.com/fjp/diffbot). I currently have a running Gazebo simulation using ROS control. Only my model doesn't look as good as yours.

Could you please tell me how you created the mesh (dae) files or where to get them exactly? And would you mind if I make use of some of your mesh files because DiffBot uses the same chassis robot kit as Littlebot?

**Comment by NestorDP** [comment]
Hi @fjp thanks,

I found most 3D models on the [grabcad](https://grabcad.com/) website, some I edited/created using [onshape](https://www.onshape.com/). As you may have seen all the littlebot meshs are here, you can use them. 

Look carefully at the URDF file, it can help you in your project and feel free to give your opnion ;) 

Good luck on your project!

**Comment by fjp** [comment]
Thank you @NestorDP for the hints and that I can use your meshes. This is really helpful :slightly_smiling_face:  I sure will review your URDF and I hope I can give you some useful feedback.

Also feel free to reuse implementations of DiffBot in case you need, and suggestions are also always welcome :wink: 

Thanks again and good luck with your project too.
